//
// Generated file, do not edit! Created by nedtool 5.2 from UserPacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __USERPACKET_M_H
#define __USERPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>UserPacket.msg:17</tt> by nedtool.
 * <pre>
 * packet UserPacket
 * {
 *     simtime_t start_time;
 * }
 * </pre>
 */
class UserPacket : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t start_time;

  private:
    void copy(const UserPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UserPacket&);

  public:
    UserPacket(const char *name=nullptr, short kind=0);
    UserPacket(const UserPacket& other);
    virtual ~UserPacket();
    UserPacket& operator=(const UserPacket& other);
    virtual UserPacket *dup() const override {return new UserPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getStart_time() const;
    virtual void setStart_time(::omnetpp::simtime_t start_time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UserPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UserPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __USERPACKET_M_H

